default:
  toolbar:
    - styleselect | bold italic | undo redo
    - image | link
  plugins:
    - image
    - link

message:
  menubar:
    - false
  toolbar:
    - image | link
  plugins:
    - image
    - link
